name: 'Only merge from - action'
description: 'Github action to close a PR if the base branch is not from expected'
inputs:
  github-token:
    description: 'Github token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
