name: "build-test"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: raulanatol/only-merge-from-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
